-- Lab 6 - INN
-- amakarew
-- Jun 2, 2023

USE `INN`;
-- Query 1
-- For each room report the total revenue for all stays and the average revenue
per stay generated by stays in the room that originated in the months of June, July, and August (combined).
Sort output in descending order by total revenue. (Output full room names).


SELECT RoomName, SUM(Rate * DateDiff(CheckOut,CheckIn)) AS TotalRev, 
    AVG(Rate * DateDiff(CheckOut,CheckIn)) AS AveragePerStay
FROM reservations JOIN rooms ON RoomCode = Room
WHERE Month(CheckIn) >= 6 AND Month(CheckIn) <= 8
GROUP BY RoomName
ORDER BY TotalRev DESC;


USE `INN`;
-- Query 2
-- Report the total number of reservations in 2010 that commenced on Mondays  
and ended on Saturdays and the total revenue they brought in.



SELECT COUNT(*), SUM(Rate * DateDiff(CheckOut,CheckIn))
FROM reservations
WHERE DayName(CheckIn) = 'Monday' AND DayName(Checkout) = 'Saturday'
GROUP BY DayName(CheckIn);


USE `INN`;
-- Query 3
-- For each day of the week, report the total number of reservations  longer than five (5) days that commenced on it and the total revenue these reservations brought. Report days of week
as Monday, Tuesday, etc.  Sort output by day of week (Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday)

(NOTE: this query is a bit nasty, but is very doable. You may need the built-in MOD() function)

SELECT DayName(CheckIn), COUNT(*) as Stays, 
    SUM(Rate * DateDiff(CheckOut,CheckIn))
FROM reservations
WHERE DATEDIFF(CheckOut, Checkin) > 5
GROUP BY Weekday(CheckIn), DayName(CheckIn)
ORDER BY Weekday(CheckIn);


USE `INN`;
-- Query 4
--  For each room report the total number of people who stayed in it in 2010 (all reservations that started in 2010).
Report full names of the rooms, sort in descending order by the total number of people.


SELECT RoomName, SUM(Adults) + SUM(Kids)
FROM reservations JOIN rooms ON RoomCode = Room
WHERE CheckIn >= '2010-01-01' AND CheckIn <= '2010-12-31'
GROUP BY RoomName
ORDER BY SUM(Adults) + SUM(Kids) DESC;


USE `INN`;
-- Query 5
--  For each room report how many nights in 2010 the room was occupied.
Report the room code, the full name of the room and the number of occupied nights. Sort in descending order by occupied nights.

Note: it has to be number of nights in 2010 - the last reservation
in each room may and will go beyond December 31, 2010, so the
"extra" nights in 2011 need to be deducted.


Note/Hint: This is  almost an extra credit problem.  While multiple solutions
are possible, my solution uses SQL's SIGN() built-in function which returns -1
for negative numbers, +1 for positive numbers, and 0 for 0.



SELECT res.Room, ro.RoomName, SUM(
    CASE
    WHEN CheckIn >= '2010-01-01' AND Checkout <= '2010-12-31' 
        THEN DATEDIFF(CheckOut, CheckIn)
    WHEN CheckIn < "2010-01-01" AND Checkout <= '2010-12-31' 
        THEN DATEDIFF(Checkout, '2010-01-01')
    WHEN CheckIn >= '2010-01-01' AND Checkout > "2010-12-31" 
        THEN DATEDIFF("2010-12-31", CheckIn)
    
    ELSE 365
    END)
    AS Days 
FROM reservations AS res, rooms AS ro
WHERE ro.RoomCode = res.Room AND Checkout >= '2010-01-01' 
    AND CheckIn <= '2010-12-31'
GROUP BY Room
ORDER BY Days DESC;


